---
linters:
  enable-all: true
  disable:
    - wsl
    - err113
    - nlreturn
    - lll
    - godot
    - godox
    - varnamelen
    - exhaustruct
    - depguard
    - copyloopvar # WARN [linters_context] copyloopvar: this linter is disabled because the Go version (1.19) of your project is lower than Go 1.22 
    - intrange # WARN [linters_context] intrange: this linter is disabled because the Go version (1.19) of your project is lower than Go 1.22
    - tenv # WARN The linter 'tenv' is deprecated (since v1.64.0) due to: Duplicate feature in another linter. Replaced by usetesting. 
