---
name: test
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.0'
      - run: go mod download
      - name: test
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          bash ci/test.sh github-comment-metadata
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.33
