---
name: test
on:
  pull_request:
    branches: [main]
jobs:
  status-check:
    runs-on: ubuntu-24.04
    if: always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled'))
    timeout-minutes: 10
    permissions: {}
    needs:
      - test
    steps:
      - run: exit 1
  test:
    uses: suzuki-shunsuke/go-test-full-workflow/.github/workflows/test.yaml@10238675cfaeb021a013ac656c58babe6ff69a62 # v5.0.0
    with:
      aqua_version: v2.55.0
      go-version-file: go.mod
    permissions:
      pull-requests: write
      contents: read # To checkout private repository
